/**
 * tea_library_translations.js
 * Chai Holistic — Tea Library blend translations
 * All 40 blends × 5 languages (es, fr, pt, ht, jm)
 *
 * Usage:
 *   import { getTLBlend } from "./tea_library_translations";
 *   const t = getTLBlend(blend.n, lang);
 *   if (t) { use t.name, t.benefits, t.brew, t.tip }
 */

const TL_TRANS = {

1: {
  es: { name:"Mezcla para Dormir Profundo y Calma", benefits:"Promueve un sueño profundo y reparador y alivia la ansiedad. La valeriana y la pasiflora calman el sistema nervioso, mientras que la lavanda y la melisa reducen el ruido mental antes de dormir.", brew:"Infusiona 1–2 cdta por taza durante 7–10 min en agua casi hirviendo. Bebe 30 min antes de acostarte.", tip:"Añade una gota de miel cruda para una relajación extra." },
  fr: { name:"Mélange Sommeil Profond & Sérénité", benefits:"Favorise un sommeil profond et réparateur et apaise l'anxiété. La valériane et la passiflore calment le système nerveux, tandis que la lavande et la mélisse réduisent l'agitation mentale avant de dormir.", brew:"Infusez 1–2 c. à café par tasse pendant 7–10 min dans de l'eau presque bouillante. Buvez 30 min avant de vous coucher.", tip:"Ajoutez une goutte de miel cru pour une relaxation supplémentaire." },
  pt: { name:"Mistura para Sono Profundo e Calma", benefits:"Promove sono profundo e reparador e alivia a ansiedade. Valeriana e maracujá acalmam o sistema nervoso, enquanto lavanda e melissa reduzem o ruído mental antes de dormir.", brew:"Infunda 1–2 col. chá por xícara por 7–10 min em água quase fervente. Beba 30 min antes de dormir.", tip:"Adicione uma gota de mel cru para relaxamento extra." },
  ht: { name:"Melanj pou Dòmi Fon ak Kàlm", benefits:"Pwomouvwa yon dòmi fon ak repozan epi soulaje anxiete. Valeryan ak pasiflè kalman sistèm nève, pandan lavann ak meliz redui bri mantal anvan dòmi.", brew:"Enfize 1–2 ti kiyè pou chak tas pou 7–10 min nan dlo prèske bouyi. Bwè 30 min anvan ou kouche.", tip:"Ajoute yon gout myèl kri pou plis rilaks." },
  jm: { name:"Deep Sleep & Calm Blend", benefits:"Promotes deep restful sleep and ease anxiety. Valerian and passionflower calm di nervous system, while lavender and lemon balm quiet di mind before bed.", brew:"Steep 1–2 tsp per cup fi 7–10 min in near-boiling water. Drink 30 min before bed.", tip:"Add a drop of raw honey fi extra relaxation." },
},

2: {
  es: { name:"Tónico para el Corazón y la Circulación", benefits:"Apoya la salud cardiovascular fortaleciendo el músculo cardíaco, mejorando la circulación y reduciendo naturalmente la presión arterial. Rico en antioxidantes y vitamina C.", brew:"Infusiona 1–2 cdta por taza durante 8–10 min. Disfruta por la mañana o por la tarde.", tip:"Añade una rodaja de naranja para vitamina C extra." },
  fr: { name:"Tonique Cœur & Circulation", benefits:"Soutient la santé cardiovasculaire en renforçant le muscle cardiaque, en améliorant la circulation et en réduisant naturellement la tension artérielle. Riche en antioxydants et en vitamine C.", brew:"Infusez 1–2 c. à café par tasse pendant 8–10 min. Appréciez le matin ou l'après-midi.", tip:"Ajoutez une tranche d'orange pour de la vitamine C supplémentaire." },
  pt: { name:"Tônico para o Coração e Circulação", benefits:"Apoia a saúde cardiovascular fortalecendo o músculo cardíaco, melhorando a circulação e reduzindo naturalmente a pressão arterial. Rico em antioxidantes e vitamina C.", brew:"Infunda 1–2 col. chá por xícara por 8–10 min. Aprecie pela manhã ou à tarde.", tip:"Adicione uma fatia de laranja para vitamina C extra." },
  ht: { name:"Tonik pou Kè ak Sikilasyon", benefits:"Sipòte sante kadyovaskilè pandan li ranfòse misk kè, amelyore sikilasyon, epi redui presyon san natirèlman. Rich nan antioxidan ak vitamin C.", brew:"Enfize 1–2 ti kiyè pou chak tas pou 8–10 min. Jwi maten oswa apremidi.", tip:"Ajoute yon tranch zoranj pou plis vitamin C." },
  jm: { name:"Heart & Circulation Tonic", benefits:"Supports cardiovascular health by strengthening di heart muscle, improving circulation, and naturally lowering blood pressure. Rich in antioxidants and vitamin C.", brew:"Steep 1–2 tsp per cup fi 8–10 min. Enjoy morning or afternoon.", tip:"Add a slice of orange fi extra vitamin C." },
},

3: {
  es: { name:"Mezcla para el Enfoque y la Claridad Mental", benefits:"Agudiza la concentración y la memoria. El ginkgo y la gotu kola aumentan el flujo sanguíneo al cerebro, mientras que la menta y el romero estimulan el estado de alerta sin nerviosismo por la cafeína.", brew:"Infusiona 1–2 cdta por taza durante 5–7 min. Ideal a media mañana.", tip:"Inhala el vapor antes de beber para un impulso de aromaterapia." },
  fr: { name:"Mélange Concentration & Clarté Mentale", benefits:"Affine la concentration et la mémoire. Le ginkgo et le gotu kola augmentent le flux sanguin vers le cerveau, tandis que la menthe et le romarin stimulent la vigilance sans nervosité due à la caféine.", brew:"Infusez 1–2 c. à café par tasse pendant 5–7 min. Idéal en milieu de matinée.", tip:"Inhalez la vapeur avant de boire pour un boost d'aromathérapie." },
  pt: { name:"Mistura para Foco e Clareza Mental", benefits:"Aguça a concentração e a memória. Ginkgo e gotu kola aumentam o fluxo sanguíneo para o cérebro, enquanto hortelã e alecrim estimulam o estado de alerta sem o nervosismo da cafeína.", brew:"Infunda 1–2 col. chá por xícara por 5–7 min. Ideal no meio da manhã.", tip:"Inale o vapor antes de beber para um impulso de aromaterapia." },
  ht: { name:"Melanj pou Konsantrasyon ak Klète Mantal", benefits:"Amelyore konsantrasyon ak memwa. Ginkgo ak gotu kola ogmante flou san nan sèvo, pandan mint ak wozmarenn stimile vijilans san nervozite kafeyèn.", brew:"Enfize 1–2 ti kiyè pou chak tas pou 5–7 min. Ideyal nan mitan maten.", tip:"Respire vapè a anvan ou bwè pou yon bous aromaterapi." },
  jm: { name:"Focus & Mental Clarity Blend", benefits:"Sharpens concentration and memory. Ginkgo and gotu kola increase blood flow to di brain, while peppermint and rosemary stimulate alertness without caffeine jitters.", brew:"Steep 1–2 tsp per cup fi 5–7 min. Ideal mid-morning.", tip:"Inhale di steam before drinking fi an aromatherapy boost." },
},

4: {
  es: { name:"Mezcla de Defensa Inmune", benefits:"Un potente refuerzo inmunológico. El saúco y la equinácea combaten los virus, el astrágalo construye resiliencia inmune a largo plazo, y la cúrcuma con pimienta negra aporta un potente apoyo antiinflamatorio.", brew:"Hierve las raíces 10 min, infusiona las bayas 5 min. Usa 2 cdta por taza.", tip:"Añade jugo de limón fresco para activar los compuestos del saúco." },
  fr: { name:"Mélange Défense Immunitaire", benefits:"Un puissant stimulant immunitaire. Le sureau et l'échinacée combattent les virus, l'astragale renforce la résilience immunitaire à long terme, et le curcuma avec le poivre noir apporte un soutien anti-inflammatoire puissant.", brew:"Faites mijoter les racines 10 min, infusez les baies 5 min. Utilisez 2 c. à café par tasse.", tip:"Ajoutez du jus de citron frais pour activer les composés du sureau." },
  pt: { name:"Mistura de Defesa Imune", benefits:"Um poderoso reforço imunológico. Sabugueiro e equinácea combatem vírus, astrágalo constrói resiliência imune de longo prazo, e cúrcuma com pimenta-preta fornece suporte anti-inflamatório potente.", brew:"Ferva as raízes por 10 min, infunda as bagas por 5 min. Use 2 col. chá por xícara.", tip:"Adicione suco de limão fresco para ativar os compostos do sabugueiro." },
  ht: { name:"Melanj Defans Iminite", benefits:"Yon ranfòsman iminite pwisan. Siri ak ekinase konbat viris, astragal konstwi rezistans iminite alontèm, epi toumèrik ak pwèv nwa bay sipò anti-enflamatwa pwisan.", brew:"Fè rasin yo mijoté 10 min, enfize bayi yo 5 min. Itilize 2 ti kiyè pou chak tas.", tip:"Ajoute ji sitwon frèch pou aktive konpoze siri yo." },
  jm: { name:"Immune Defense Blend", benefits:"A powerful immune booster. Elderberry and echinacea fight viruses, astragalus builds long-term immune resilience, and turmeric wid black pepper deliver potent anti-inflammatory support.", brew:"Simmer roots 10 min, steep berries 5 min. Use 2 tsp per cup.", tip:"Add fresh lemon juice to activate di elderberry compounds." },
},

5: {
  es: { name:"Fuego Metabólico y Digestivo", benefits:"Estimula la digestión, reduce la hinchazón y apoya la desintoxicación hepática. La raíz de diente de león es un tónico hepático suave, mientras que el hinojo y el cardamomo alivian los calambres y los gases.", brew:"Infusiona 2 cdta por taza durante 7–10 min después de las comidas.", tip:"Excelente después de comidas pesadas para prevenir la hinchazón." },
  fr: { name:"Feu Métabolique & Digestif", benefits:"Stimule la digestion, réduit les ballonnements et soutient la détoxification hépatique. La racine de pissenlit est un tonique hépatique doux, tandis que le fenouil et la cardamome soulagent les crampes et les gaz.", brew:"Infusez 2 c. à café par tasse pendant 7–10 min après les repas.", tip:"Excellent après les repas lourds pour prévenir les ballonnements." },
  pt: { name:"Fogo Metabólico e Digestivo", benefits:"Estimula a digestão, reduz o inchaço e apoia a desintoxicação hepática. Raiz de dente-de-leão é um tônico hepático suave, enquanto funcho e cardamomo aliviam cólicas e gases.", brew:"Infunda 2 col. chá por xícara por 7–10 min após as refeições.", tip:"Excelente após refeições pesadas para prevenir inchaço." },
  ht: { name:"Dife Metabolik ak Dijestif", benefits:"Stimile dijestion, redui anfle epi sipòte detoksifikasyon fwa. Rasin pisanlit se yon tonik fwa dou pandan fenouy ak kardamòm soulaje spazm ak gaz.", brew:"Enfize 2 ti kiyè pou chak tas pou 7–10 min apre repa.", tip:"Ekselan apre repa lou pou prevni anfle." },
  jm: { name:"Metabolism & Digestive Fire", benefits:"Stimulates digestion, reduces bloating, and supports liver detoxification. Dandelion root is a gentle liver tonic while fennel and cardamom ease cramping and gas.", brew:"Steep 2 tsp per cup fi 7–10 min after meals.", tip:"Excellent after heavy meals to prevent bloating." },
},

6: {
  es: { name:"Mezcla Anti-Inflamatoria y Alivio Articular", benefits:"Combate la inflamación crónica y el dolor articular. La cúrcuma y la boswellia son estudiadas clínicamente para reducir los marcadores inflamatorios, mientras que el jengibre añade alivio del dolor con calor.", brew:"Infusiona 2 cdta por taza durante 10 min. Añade leche de coco para mejorar la absorción de curcumina.", tip:"Combina con una grasa saludable como aceite de coco para mejores resultados." },
  fr: { name:"Mélange Anti-Inflammation & Soulagement Articulaire", benefits:"Cible l'inflammation chronique et les douleurs articulaires. Le curcuma et la boswellie sont cliniquement étudiés pour réduire les marqueurs inflammatoires, tandis que le gingembre apporte un soulagement réchauffant de la douleur.", brew:"Infusez 2 c. à café par tasse pendant 10 min. Ajoutez du lait de coco pour améliorer l'absorption de la curcumine.", tip:"Combinez avec une graisse saine comme l'huile de coco pour de meilleurs résultats." },
  pt: { name:"Mistura Anti-Inflamatória e Alívio Articular", benefits:"Combate inflamação crônica e dor articular. Cúrcuma e boswellia são clinicamente estudadas para reduzir marcadores inflamatórios, enquanto gengibre adiciona alívio da dor com calor.", brew:"Infunda 2 col. chá por xícara por 10 min. Adicione leite de coco para melhorar a absorção da curcumina.", tip:"Combine com gordura saudável como óleo de coco para melhores resultados." },
  ht: { name:"Melanj Anti-Enflamatwa ak Soulajman Jwenti", benefits:"Vize enflamasyon kwonik ak doulè jwenti. Toumèrik ak boswellia etidye klinikman pou redui makè enflamatwa, pandan jenjann ajoute soulajman doulè chofe.", brew:"Enfize 2 ti kiyè pou chak tas pou 10 min. Ajoute lèt kokoye pou amelyore absòpsyon kirkumin.", tip:"Konbine ak yon grès ki bon tankou lwil kokoye pou pi bon rezilta." },
  jm: { name:"Anti-Inflammation & Joint Relief", benefits:"Targets chronic inflammation and joint pain. Turmeric and boswellia are clinically studied for reducing inflammatory markers, while ginger add warming pain relief.", brew:"Steep 2 tsp per cup fi 10 min. Add coconut milk to enhance curcumin absorption.", tip:"Combine wid a healthy fat like coconut oil fi best results." },
},

7: {
  es: { name:"Equilibrio Hormonal y Bienestar Femenino", benefits:"Apoya el equilibrio hormonal, alivia los síntomas del SPM y regula los ciclos. La agnocasto actúa sobre la glándula pituitaria y la ashwagandha ayuda a regular el cortisol y las hormonas del estrés.", brew:"Infusiona 2 cdta por taza durante 7 min. Bebe consistentemente durante al menos 3 ciclos.", tip:"Evita el dong quai durante la menstruación; úsalo en la fase folicular." },
  fr: { name:"Équilibre Hormonal & Bien-être Féminin", benefits:"Soutient l'équilibre hormonal, soulage les symptômes du SPM et régule les cycles. Le gattilier agit sur l'hypophyse et l'ashwagandha aide à gérer le cortisol et les hormones du stress.", brew:"Infusez 2 c. à café par tasse pendant 7 min. Buvez régulièrement pendant au moins 3 cycles.", tip:"Évitez le dong quai pendant les menstruations ; utilisez-le pendant la phase folliculaire." },
  pt: { name:"Equilíbrio Hormonal e Bem-estar Feminino", benefits:"Apoia o equilíbrio hormonal, alivia sintomas da TPM e regula os ciclos. Vitex age na hipófise e ashwagandha ajuda a regular o cortisol e os hormônios do estresse.", brew:"Infunda 2 col. chá por xícara por 7 min. Beba consistentemente por pelo menos 3 ciclos.", tip:"Evite dong quai durante a menstruação; use na fase folicular." },
  ht: { name:"Ekilibre Ormonal ak Byenèt Fanm", benefits:"Sipòte ekilibre ormonal, soulaje sentòm SPM epi regle sik. Chasteberry aji sou glann pituitè epi ashwagandha ede jere kòtizòl ak omon stres.", brew:"Enfize 2 ti kiyè pou chak tas pou 7 min. Bwè regilyèman pou omwen 3 sik.", tip:"Evite dong quai pandan règ; itilize nan faz folikilè." },
  jm: { name:"Hormone Balance & Women's Wellness", benefits:"Supports hormonal balance, eases PMS symptoms, and regulates cycles. Chasteberry act on di pituitary gland and ashwagandha help manage cortisol and stress hormones.", brew:"Steep 2 tsp per cup fi 7 min. Drink consistently fi at least 3 cycles.", tip:"Avoid dong quai during menstruation; use in di follicular phase." },
},

8: {
  es: { name:"Claridad Pulmonar y Respiratoria", benefits:"Abre las vías respiratorias, elimina el moco y suaviza el tejido pulmonar irritado. El gordolobo es una de las hierbas más confiables para la salud respiratoria, y el tomillo actúa como antimicrobiano natural.", brew:"Infusiona 2 cdta por taza durante 8 min. Inhala el vapor antes de beber.", tip:"Añade miel de manuka cruda para una acción antimicrobiana adicional." },
  fr: { name:"Clarté Pulmonaire & Respiratoire", benefits:"Ouvre les voies respiratoires, dissout le mucus et apaise les tissus pulmonaires irrités. La molène est l'une des herbes les plus fiables pour la santé respiratoire, et le thym agit comme antimicrobien naturel.", brew:"Infusez 2 c. à café par tasse pendant 8 min. Inhalez la vapeur avant de boire.", tip:"Ajoutez du miel de manuka cru pour une action antimicrobienne supplémentaire." },
  pt: { name:"Clareza Pulmonar e Respiratória", benefits:"Abre as vias respiratórias, elimina muco e suaviza o tecido pulmonar irritado. Verbasco é uma das ervas mais confiáveis para saúde respiratória, e tomilho age como antimicrobiano natural.", brew:"Infunda 2 col. chá por xícara por 8 min. Inale o vapor antes de beber.", tip:"Adicione mel de manuka cru para ação antimicrobiana adicional." },
  ht: { name:"Klète Poumon ak Respiratwa", benefits:"Ouvri vwa respiratwa, retire mik epi kalman tisi poumon irité. Gordon lou se youn nan zèb ki pi fòb pou sante respiratwa, epi tim aji kòm yon antimikwòb natirèl.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min. Respire vapè a anvan ou bwè.", tip:"Ajoute myèl manuka kri pou plis aksyon antimikwòb." },
  jm: { name:"Lung & Respiratory Clarity", benefits:"Opens airways, clears mucus, and soothes irritated lung tissue. Mullein is one of di most trusted herbs for respiratory health, and thyme acts as a natural antimicrobial.", brew:"Steep 2 tsp per cup fi 8 min. Inhale steam before drinking.", tip:"Add raw manuka honey fi added antimicrobial action." },
},

9: {
  es: { name:"Mezcla Adaptógena de Energía y Vitalidad", benefits:"Combate la fatiga y construye resiliencia al estrés sin estimulantes. Estos adaptógenos equilibran el cortisol, apoyan la salud suprarrenal y proporcionan energía sostenida durante el día.", brew:"Hierve a fuego lento 2 cdta por taza durante 10–15 min. Bebe por la mañana.", tip:"Toma consistentemente durante 4–6 semanas para sentir todos los beneficios adaptogénicos." },
  fr: { name:"Mélange Adaptogène Énergie & Vitalité", benefits:"Combat la fatigue et renforce la résistance au stress sans stimulants. Ces adaptogènes équilibrent le cortisol, soutiennent la santé surrénale et fournissent une énergie soutenue tout au long de la journée.", brew:"Faites mijoter 2 c. à café par tasse pendant 10–15 min. Buvez le matin.", tip:"Prenez régulièrement pendant 4–6 semaines pour ressentir tous les bienfaits adaptogènes." },
  pt: { name:"Mistura Adaptogênica de Energia e Vitalidade", benefits:"Combate a fadiga e constrói resiliência ao estresse sem estimulantes. Esses adaptógenos equilibram o cortisol, apoiam a saúde adrenal e fornecem energia sustentada ao longo do dia.", brew:"Ferva em fogo baixo 2 col. chá por xícara por 10–15 min. Beba pela manhã.", tip:"Tome consistentemente por 4–6 semanas para sentir todos os benefícios adaptogênicos." },
  ht: { name:"Melanj Adaptojèn Enèji ak Vitalite", benefits:"Konbat fatig epi konstwi rezistans stres san stimilan. Adaptojèn sa yo ekilibre kòtizòl, sipòte sante adrenal epi bay enèji soutni pandan tout jounen.", brew:"Mijoté 2 ti kiyè pou chak tas pou 10–15 min. Bwè maten an.", tip:"Pran regilyèman pou 4–6 semèn pou santi tout benefis adaptojèn yo." },
  jm: { name:"Adaptogen Energy & Vitality Blend", benefits:"Combats fatigue and builds stress resilience without stimulants. These adaptogens balance cortisol, support adrenal health, and provide sustained energy throughout di day.", brew:"Simmer 2 tsp per cup fi 10–15 min. Drink in di morning.", tip:"Take consistently fi 4–6 weeks to feel full adaptogenic benefits." },
},

10: {
  es: { name:"Mezcla Curativa del Intestino y el Microbioma", benefits:"Repara y suaviza el revestimiento intestinal, ideal para intestino permeable, SII o inflamación. El olmo resbaladizo y la raíz de malvavisco recubren y curan la pared intestinal mientras la caléndula reduce la inflamación intestinal.", brew:"Remojo en frío 2 cdta por taza durante toda la noche para máxima extracción de mucílago.", tip:"No tomes dentro de las 2 horas siguientes a los medicamentos ya que puede ralentizar la absorción." },
  fr: { name:"Mélange Guérison Intestinale & Microbiome", benefits:"Répare et apaise la muqueuse intestinale, idéal pour l'intestin perméable, le SCI ou l'inflammation. L'orme glissant et la racine de guimauve enduisent et guérissent la paroi intestinale tandis que le calendula réduit l'inflammation intestinale.", brew:"Laissez infuser à froid 2 c. à café par tasse toute la nuit pour une extraction maximale de mucilage.", tip:"Ne prenez pas dans les 2 heures suivant les médicaments car cela peut ralentir l'absorption." },
  pt: { name:"Mistura de Cura Intestinal e Microbioma", benefits:"Repara e suaviza o revestimento intestinal, ideal para intestino permeável, SII ou inflamação. Olmo escorregadio e raiz de marshmallow revestem e curam a parede intestinal enquanto calêndula reduz a inflamação intestinal.", brew:"Deixe em infusão fria 2 col. chá por xícara durante a noite para máxima extração de mucilagem.", tip:"Não tome dentro de 2 horas de medicamentos pois pode retardar a absorção." },
  ht: { name:"Melanj Gerizon Trip ak Mikwòbyòm", benefits:"Repare epi kalman revètman trip, ideyal pou intestin pèmeyab, IBS oswa enflamasyon. Olm glisan ak rasin marshmallow kouvri epi geri mi trip pandan kalandila redui enflamasyon trip.", brew:"Trempé frèt 2 ti kiyè pou chak tas tout nuit pou maksimòm ekstraksyon misilaj.", tip:"Pa pran nan 2 èdtan medikaman paske li ka ralanti absòpsyon." },
  jm: { name:"Gut Healing & Microbiome Blend", benefits:"Repairs and soothes di gut lining, ideal for leaky gut, IBS, or inflammation. Slippery elm and marshmallow root coat and heal di intestinal wall while calendula reduces gut inflammation.", brew:"Cold-steep 2 tsp per cup overnight fi maximum mucilage extraction.", tip:"Do not take within 2 hours of medications as it may slow absorption." },
},

11: {
  es: { name:"Mezcla Desintoxicante Niebla Oceánica", benefits:"Una fórmula de desintoxicación rara entre océano y tierra. El bladderwrack y la espirulina extraen metales pesados y toxinas del cuerpo mientras proporcionan yodo rico para el apoyo tiroideo.", brew:"Infusiona 2 cdta por taza durante 6–8 min. Bebe lo primero por la mañana.", tip:"Mejor tomada como programa de limpieza de 7 días, dos veces al día." },
  fr: { name:"Mélange Détox Brume Océanique", benefits:"Une rare formule détox entre océan et terre. Le bladderwrack et la spiruline extraient les métaux lourds et les toxines du corps tout en fournissant de l'iode pour le soutien thyroïdien.", brew:"Infusez 2 c. à café par tasse pendant 6–8 min. Buvez dès le matin.", tip:"Mieux pris comme programme de nettoyage de 7 jours, deux fois par jour." },
  pt: { name:"Mistura Detox Névoa Oceânica", benefits:"Uma rara fórmula detox entre oceano e terra. Bladderwrack e espirulina extraem metais pesados e toxinas do corpo enquanto fornecem iodo rico para suporte tireoidiano.", brew:"Infunda 2 col. chá por xícara por 6–8 min. Beba logo pela manhã.", tip:"Melhor tomado como programa de limpeza de 7 dias, duas vezes ao dia." },
  ht: { name:"Melanj Detoks Bwouya Osean", benefits:"Yon fòmil detoks ra ant osean ak tè. Bladderwrack ak spirulin retire metal lou ak toksin nan kò pandan y ap bay iod rich pou sipò tiroyid.", brew:"Enfize 2 ti kiyè pou chak tas pou 6–8 min. Bwè premye bagay maten an.", tip:"Pi bon pran kòm pwogram netwayaj 7 jou, de fwa pa jou." },
  jm: { name:"Ocean Mist Detox Blend", benefits:"A rare ocean-meets-earth detox formula. Bladderwrack and spirulina pull heavy metals and toxins from di body while providing rich iodine fi thyroid support.", brew:"Steep 2 tsp per cup fi 6–8 min. Drink first thing in di morning.", tip:"Best taken as a 7-day cleanse program, twice daily." },
},

12: {
  es: { name:"Mezcla de Claridad del Tercer Ojo", benefits:"Una antigua mezcla visionaria usada en tradiciones egipcias, ayurvédicas e indígenas. El artemisa y el loto azul mejoran la claridad de los sueños y la intuición.", brew:"Infusiona 2 cdta por taza durante 7 min justo por debajo de la ebullición. Bebe antes de meditar.", tip:"Ten un diario de sueños cerca — esta mezcla puede intensificar el recuerdo de los sueños." },
  fr: { name:"Mélange Clarté du Troisième Œil", benefits:"Un ancien mélange visionnaire utilisé dans les traditions égyptienne, ayurvédique et indigène. L'armoise et le lotus bleu améliorent la clarté des rêves et l'intuition.", brew:"Infusez 2 c. à café par tasse pendant 7 min juste en dessous de l'ébullition. Buvez avant de méditer.", tip:"Gardez un journal des rêves à portée de main — ce mélange peut intensifier le souvenir des rêves." },
  pt: { name:"Mistura de Clareza do Terceiro Olho", benefits:"Uma antiga mistura visionária usada nas tradições egípcia, ayurvédica e indígena. Artemísia e lótus azul melhoram a clareza dos sonhos e a intuição.", brew:"Infunda 2 col. chá por xícara por 7 min abaixo da fervura. Beba antes de meditar.", tip:"Mantenha um diário de sonhos por perto — esta mistura pode intensificar a lembrança dos sonhos." },
  ht: { name:"Melanj Klète Twazyèm Je", benefits:"Yon ansyen melanj vizyonè itilize nan tradisyon ejipsyen, ayirvédik ak endijèn. Mugwort ak flè loti ble amelyore klète rèv ak entwiyon.", brew:"Enfize 2 ti kiyè pou chak tas pou 7 min jis anba bouyi. Bwè anvan meditasyon.", tip:"Kenbe yon jounal rèv toupre — melanj sa a ka entansifye rapèl rèv." },
  jm: { name:"Third Eye Clarity Blend", benefits:"An ancient visionary blend used across Egyptian, Ayurvedic, and indigenous traditions. Mugwort and blue lotus enhance dream clarity and intuition.", brew:"Steep 2 tsp per cup fi 7 min just below boiling. Drink before meditation.", tip:"Keep a dream journal nearby — dis blend may intensify dream recall." },
},

13: {
  es: { name:"Mezcla Metamorfosis para Levantar el Ánimo", benefits:"Un antidepresivo natural suave pero poderoso. La hierba de San Juan y el azafrán son estudiados clínicamente para levantar la depresión leve a moderada.", brew:"Infusiona 2 cdta por taza durante 6–8 min. Bebe consistentemente cada mañana.", tip:"La hierba de San Juan interactúa con muchos medicamentos — consulta a tu médico primero." },
  fr: { name:"Mélange Métamorphose Élévation d'Humeur", benefits:"Un antidépresseur naturel doux mais puissant. Le millepertuis et le safran sont cliniquement étudiés pour soulever la dépression légère à modérée.", brew:"Infusez 2 c. à café par tasse pendant 6–8 min. Buvez régulièrement chaque matin.", tip:"Le millepertuis interagit avec de nombreux médicaments — consultez d'abord votre médecin." },
  pt: { name:"Mistura Metamorfose para Elevar o Humor", benefits:"Um antidepressivo natural suave, mas poderoso. Erva-de-são-joão e açafrão são clinicamente estudados para levantar a depressão leve a moderada.", brew:"Infunda 2 col. chá por xícara por 6–8 min. Beba consistentemente toda manhã.", tip:"Erva-de-são-joão interage com muitos medicamentos — consulte seu médico primeiro." },
  ht: { name:"Melanj Metamòfoz pou Leve Emosyon", benefits:"Yon antidepresè natirèl dou men pwisan. Zèb Sen Jan ak safran etidye klinikman pou soulve depresyon modere.", brew:"Enfize 2 ti kiyè pou chak tas pou 6–8 min. Bwè regilyèman chak maten.", tip:"Zèb Sen Jan entèraji ak anpil medikaman — konsite doktè ou an premye." },
  jm: { name:"Metamorphosis Mood Lift Blend", benefits:"A gentle yet powerful natural antidepressant formula. St. John's Wort and saffron are clinically studied fi lifting mild to moderate depression.", brew:"Steep 2 tsp per cup fi 6–8 min. Drink consistently each morning.", tip:"St. John's Wort interacts wid many medications — consult yuh doctor first." },
},

14: {
  es: { name:"Mezcla de Longevidad Fuego del Dragón", benefits:"Inspirado en las antiguas tradiciones chinas de longevidad. El he shou wu nutre la sangre y los riñones, el reishi apoya la inteligencia inmunológica y los genes de longevidad.", brew:"Hierve a fuego lento 2 cdta por taza durante 15–20 min para una decocción rica.", tip:"Esta mezcla mejora con el uso consistente durante 3+ meses." },
  fr: { name:"Mélange Longévité Feu du Dragon", benefits:"Inspiré des anciennes traditions chinoises de longévité. He shou wu nourrit le sang et les reins, le reishi soutient l'intelligence immunitaire et les gènes de longévité.", brew:"Faites mijoter 2 c. à café par tasse pendant 15–20 min pour une décoction riche.", tip:"Ce mélange s'améliore avec une utilisation régulière sur 3+ mois." },
  pt: { name:"Mistura Longevidade Fogo do Dragão", benefits:"Inspirado nas antigas tradições chinesas de longevidade. He shou wu nutre o sangue e os rins, reishi apoia a inteligência imune e os genes de longevidade.", brew:"Ferva em fogo baixo 2 col. chá por xícara por 15–20 min para uma decocção rica.", tip:"Esta mistura melhora com uso consistente por 3+ meses." },
  ht: { name:"Melanj Lonjevite Dife Dragon", benefits:"Enspire pa ansyen tradisyon lonjevite chinwa. He shou wu nouri san ak renn, reishi sipòte entèlijans iminite ak jèn lonjevite.", brew:"Mijoté 2 ti kiyè pou chak tas pou 15–20 min pou yon dekoktyon rich.", tip:"Melanj sa a amelyore ak itilizasyon konsistan sou 3+ mwa." },
  jm: { name:"Dragon Fire Longevity Blend", benefits:"Inspired by ancient Chinese longevity traditions. He shou wu nourishes di blood and kidneys, reishi supports immune intelligence and longevity genes.", brew:"Simmer 2 tsp per cup fi 15–20 min fi a rich decoction.", tip:"Dis blend improves wid consistent use over 3+ months." },
},

15: {
  es: { name:"Mezcla de Belleza Venus", benefits:"Una mezcla de belleza que trabaja desde adentro. El polvo de perla y la rosa mosqueta aportan nutrientes que aumentan el colágeno, el trébol rojo apoya la elasticidad de la piel.", brew:"Infusiona 2 cdta por taza durante 7 min. Añade un toque de agua de rosas.", tip:"Bebe diariamente durante 30 días para mejoras visibles en piel, cabello y uñas." },
  fr: { name:"Mélange Beauté Vénus", benefits:"Un mélange de beauté qui agit de l'intérieur vers l'extérieur. La poudre de nacre et le cynorrhodon apportent des nutriments stimulant le collagène, le trèfle rouge soutient l'élasticité de la peau.", brew:"Infusez 2 c. à café par tasse pendant 7 min. Ajoutez une touche d'eau de rose.", tip:"Buvez quotidiennement pendant 30 jours pour des améliorations visibles de la peau, des cheveux et des ongles." },
  pt: { name:"Mistura de Beleza Vênus", benefits:"Uma mistura de beleza que trabalha de dentro para fora. Pó de pérola e rosa mosqueta fornecem nutrientes que aumentam o colágeno, trevo vermelho apoia a elasticidade da pele.", brew:"Infunda 2 col. chá por xícara por 7 min. Adicione um toque de água de rosas.", tip:"Beba diariamente por 30 dias para melhorias visíveis na pele, cabelo e unhas." },
  ht: { name:"Melanj Bote Venis", benefits:"Yon melanj bote ki travay depi anndan. Poud pèl ak kwit woz bay nourisan ki ogmante kolajen, trefle wouj sipòte elastisite po.", brew:"Enfize 2 ti kiyè pou chak tas pou 7 min. Ajoute yon ti dlo woz.", tip:"Bwè chak jou pou 30 jou pou amelyorasyon vizib nan po, cheve ak zong." },
  jm: { name:"Venus Beauty Blend", benefits:"A beauty blend weh works from di inside out. Pearl powder and rose hip deliver collagen-boosting nutrients, red clover supports skin elasticity.", brew:"Steep 2 tsp per cup fi 7 min. Add a splash of rosewater.", tip:"Drink daily fi 30 days fi visible skin, hair, and nail improvements." },
},

16: {
  es: { name:"Mezcla de Reparación del ADN y Renovación Celular", benefits:"Una fórmula de reparación celular de vanguardia. El astrágalo activa la telomerasa para la longevidad celular, la uña de gato repara las roturas de cadenas de ADN, la amla es una de las plantas más ricas en antioxidantes de la tierra.", brew:"Infusiona 2 cdta por taza durante 8 min. Mejor consumido por la mañana.", tip:"La semilla negra es muy potente — comienza con una pequeña pizca y aumenta gradualmente." },
  fr: { name:"Mélange Réparation ADN & Renouvellement Cellulaire", benefits:"Une formule de réparation cellulaire de pointe. L'astragale active la télomérase pour la longévité cellulaire, la griffe de chat répare les cassures des brins d'ADN, l'amla est l'une des plantes les plus riches en antioxydants sur terre.", brew:"Infusez 2 c. à café par tasse pendant 8 min. Mieux consommé le matin.", tip:"La graine noire est très puissante — commencez par une petite pincée et augmentez progressivement." },
  pt: { name:"Mistura de Reparação do DNA e Renovação Celular", benefits:"Uma fórmula de reparação celular de ponta. Astrágalo ativa a telomerase para longevidade celular, unha de gato repara quebras nas cadeias de DNA, amla é uma das plantas mais ricas em antioxidantes da terra.", brew:"Infunda 2 col. chá por xícara por 8 min. Melhor consumido pela manhã.", tip:"A semente preta é muito potente — comece com uma pequena pitada e aumente gradualmente." },
  ht: { name:"Melanj Reparasyon ADN ak Renouvèlman Selilè", benefits:"Yon fòmil reparasyon selilè avanke. Astragal aktive telomeraz pou lonjevite selilè, grif chat repare kase chayn ADN, amla se youn nan plant ki pi rich nan antioxidan sou tè.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min. Pi bon konsime maten an.", tip:"Grenn nwa trè pwisan — kòmanse ak yon ti kras epi ogmante piti piti." },
  jm: { name:"DNA Repair & Cell Renewal Blend", benefits:"A cutting-edge cellular repair formula. Astragalus activates telomerase fi cellular longevity, cat's claw repairs DNA strand breaks, amla is one of di most antioxidant-rich plants on earth.", brew:"Steep 2 tsp per cup fi 8 min. Best consumed in di morning.", tip:"Black seed is very potent — start wid a small pinch and increase gradually." },
},

17: {
  es: { name:"Trabajo con la Sombra y Reinicio del Sistema Nervioso", benefits:"Una mezcla profundamente terapéutica para el trauma, la hipervigilancia o el estrés crónico. La kava kava y la amapola de California relajan profundamente el sistema nervioso.", brew:"Infusiona 2 cdta por taza durante 8 min por la noche.", tip:"No conduzcas después de beber. Evita con alcohol." },
  fr: { name:"Travail d'Ombre & Réinitialisation du Système Nerveux", benefits:"Un mélange profondément thérapeutique pour le trauma, l'hypervigilance ou le stress chronique. Le kava kava et le pavot de Californie relaxent profondément le système nerveux.", brew:"Infusez 2 c. à café par tasse pendant 8 min le soir.", tip:"Ne conduisez pas après avoir bu. Évitez avec l'alcool." },
  pt: { name:"Trabalho com a Sombra e Reinicialização do Sistema Nervoso", benefits:"Uma mistura profundamente terapêutica para trauma, hipervigilância ou estresse crônico. Kava kava e papoula da Califórnia relaxam profundamente o sistema nervoso.", brew:"Infunda 2 col. chá por xícara por 8 min à noite.", tip:"Não dirija após beber. Evite com álcool." },
  ht: { name:"Travay Lonbraj ak Reyajisteman Sistèm Nève", benefits:"Yon melanj terapetik fon pou travma, ipèrvijilans oswa stres kwonik. Kava kava ak papo Kalifòni rilaks sistèm nève anpil.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min aswè a.", tip:"Pa kondwi apre bwè. Evite ak alkòl." },
  jm: { name:"Shadow Work & Nervous System Reset", benefits:"A deeply therapeutic blend fi trauma, hypervigilance, or chronic stress. Kava kava and California poppy deeply relax di nervous system.", brew:"Steep 2 tsp per cup fi 8 min in di evening.", tip:"Do not drive after drinking. Avoid wid alcohol." },
},

18: {
  es: { name:"Mezcla de Resistencia Guerrero Alpino", benefits:"Construida para el rendimiento físico y la resistencia. Los cordyceps aumentan la captación de oxígeno, la rhodiola retrasa la fatiga, el polen de pino proporciona fitoandrogenos naturales, y la maca aumenta la resistencia.", brew:"Hierve a fuego lento 2 cdta por taza durante 12–15 min. Bebe 45 min antes de la actividad.", tip:"Cicla esta mezcla — 5 días activo, 2 días de descanso para un efecto sostenido." },
  fr: { name:"Mélange Endurance Guerrier Alpin", benefits:"Conçu pour la performance physique et l'endurance. Les cordyceps augmentent l'absorption d'oxygène, la rhodiole retarde la fatigue, le pollen de pin fournit des phyto-androgènes naturels, et le maca booste l'endurance.", brew:"Faites mijoter 2 c. à café par tasse pendant 12–15 min. Buvez 45 min avant l'activité.", tip:"Faites des cycles — 5 jours actif, 2 jours de repos pour un effet soutenu." },
  pt: { name:"Mistura de Resistência Guerreiro Alpino", benefits:"Construída para desempenho físico e resistência. Cordyceps aumentam a captação de oxigênio, rhodiola atrasa a fadiga, pólen de pinho fornece fito-andrógenos naturais, e maca aumenta a resistência.", brew:"Ferva em fogo baixo 2 col. chá por xícara por 12–15 min. Beba 45 min antes da atividade.", tip:"Faça ciclos — 5 dias ativo, 2 dias de descanso para efeito sustentado." },
  ht: { name:"Melanj Rezistans Gèrye Alpen", benefits:"Konstwi pou pèfòmans fizik ak rezistans. Kòdisèp ogmante absòpsyon oksijèn, wodiola ralanti fatig, poud pen bay fitoandrójèn natirèl, epi maka ogmante rezistans.", brew:"Mijoté 2 ti kiyè pou chak tas pou 12–15 min. Bwè 45 min anvan aktivite.", tip:"Fè sik — 5 jou aktif, 2 jou repo pou efè soutni." },
  jm: { name:"Alpine Warrior Endurance Blend", benefits:"Built fi physical performance and stamina. Cordyceps increase oxygen uptake, rhodiola delays fatigue, pine pollen provides natural phyto-androgens, and maca boosts endurance.", brew:"Simmer 2 tsp per cup fi 12–15 min. Drink 45 min before activity.", tip:"Cycle dis blend — 5 days on, 2 days off fi sustained effect." },
},

19: {
  es: { name:"Mezcla de Arraigo Ancestral", benefits:"Enraizado en la sabiduría botánica africana. El rooibos es rico en antioxidantes únicos, el baobab aporta fibra prebiótica y vitamina C, la moringa proporciona proteína vegetal completa e hierro.", brew:"Infusiona 2 cdta por taza durante 8–10 min. Naturalmente sin cafeína.", tip:"Maravilloso como té helado — infusión en frío durante la noche en el refrigerador." },
  fr: { name:"Mélange d'Ancrage Ancestral", benefits:"Enraciné dans la sagesse botanique africaine. Le rooibos est riche en antioxydants uniques, le baobab apporte des fibres prébiotiques et de la vitamine C, la moringa fournit des protéines végétales complètes et du fer.", brew:"Infusez 2 c. à café par tasse pendant 8–10 min. Naturellement sans caféine.", tip:"Merveilleux en thé glacé — infusion froide toute la nuit au réfrigérateur." },
  pt: { name:"Mistura de Enraizamento Ancestral", benefits:"Enraizada na sabedoria botânica africana. Rooibos é rico em antioxidantes únicos, baobá fornece fibra prebiótica e vitamina C, moringa fornece proteína vegetal completa e ferro.", brew:"Infunda 2 col. chá por xícara por 8–10 min. Naturalmente sem cafeína.", tip:"Maravilhoso como chá gelado — infusão fria durante a noite na geladeira." },
  ht: { name:"Melanj Anrasinen Ansestral", benefits:"Anrasinen nan sajès botanik afriken. Rooibos rich nan antioxidan inik, baobab bay fib pwebyotik ak vitamin C, moringa bay pwoteyin plant konplè ak fè.", brew:"Enfize 2 ti kiyè pou chak tas pou 8–10 min. San kafeyèn natirèlman.", tip:"Mèveye kòm tè glase — enfizyon frèt tout nuit nan frijidè." },
  jm: { name:"Ancestral Grounding Blend", benefits:"Rooted in African botanical wisdom. Rooibos is rich in unique antioxidants, baobab delivers prebiotic fiber and vitamin C, moringa provides complete plant-based protein and iron.", brew:"Steep 2 tsp per cup fi 8–10 min. Naturally caffeine-free.", tip:"Wonderful as an iced tea — cold brew overnight in di refrigerator." },
},

20: {
  es: { name:"Mezcla de Activación Pineal Polvo de Estrellas", benefits:"Una fórmula neuro-nutritiva. El loto azul y la mucuna pruriens estimulan suavemente las vías de dopamina y serotonina, la melena de león promueve el factor de crecimiento nervioso para la regeneración cerebral.", brew:"Infusiona 2 cdta por taza durante 8 min, luego incorpora el cacao. Bebe conscientemente.", tip:"El cacao lo convierte en un hermoso té ritual matutino." },
  fr: { name:"Mélange Activation Pinéale Poussière d'Étoiles", benefits:"Une formule neuro-nourrissante. Le lotus bleu et la mucuna pruriens stimulent doucement les voies de la dopamine et de la sérotonine, la crinière de lion favorise le facteur de croissance nerveuse pour la régénération cérébrale.", brew:"Infusez 2 c. à café par tasse pendant 8 min, puis incorporez le cacao. Buvez consciemment.", tip:"Le cacao en fait un beau thé rituel matinal." },
  pt: { name:"Mistura de Ativação Pineal Pó de Estrelas", benefits:"Uma fórmula neuro-nutritiva. Lótus azul e mucuna pruriens estimulam suavemente as vias de dopamina e serotonina, juba de leão promove o fator de crescimento nervoso para regeneração cerebral.", brew:"Infunda 2 col. chá por xícara por 8 min, depois incorpore o cacau. Beba conscientemente.", tip:"O cacau o torna um lindo chá ritual matinal." },
  ht: { name:"Melanj Aktivasyon Pinal Poud Zetwal", benefits:"Yon fòmil nèwo-nouri. Loti ble ak mucuna pruriens dousman stimile vwa dopamin ak sewotonin, krin lyon pwomouvwa faktè kwisans nè pou rejenèrasyon sèvo.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min, Epi mete kakao. Bwè ak konsyans.", tip:"Kakao a fè li yon bèl tè ritiyèl maten." },
  jm: { name:"Stardust Pineal Activation Blend", benefits:"A neuro-nourishing formula. Blue lotus and mucuna pruriens gently stimulate dopamine and serotonin pathways, lion's mane promotes nerve growth factor fi brain regeneration.", brew:"Steep 2 tsp per cup fi 8 min, then whisk in cacao. Drink mindfully.", tip:"Di cacao makes dis a beautiful morning ritual tea." },
},

21: {
  es: { name:"Mezcla Sagrada de Dama de la Noche", benefits:"Una mezcla nocturna de lujo para la relajación profunda y la conexión espiritual. Las flores de dama de la noche y el jazmín crean un perfil de sabor cautivante mientras inducen la calma.", brew:"Infusiona 1–2 cdta por taza durante 5–7 min justo antes de acostarte.", tip:"Crea un ambiente tranquilo — atenúa las luces y bebe en silencio." },
  fr: { name:"Mélange Sacré Dame de la Nuit", benefits:"Un mélange nocturne luxueux pour une relaxation profonde et une connexion spirituelle. Les fleurs de dame de la nuit et le jasmin créent un profil gustatif envoûtant tout en induisant la sérénité.", brew:"Infusez 1–2 c. à café par tasse pendant 5–7 min juste avant de vous coucher.", tip:"Créez une ambiance calme — tamisez les lumières et buvez en silence." },
  pt: { name:"Mistura Sagrada Dama da Noite", benefits:"Uma mistura noturna luxuosa para relaxamento profundo e conexão espiritual. Flores de dama da noite e jasmim criam um perfil de sabor cativante enquanto induzem a calma.", brew:"Infunda 1–2 col. chá por xícara por 5–7 min logo antes de dormir.", tip:"Crie um ambiente tranquilo — reduza as luzes e beba em silêncio." },
  ht: { name:"Melanj Sakre Dam Nuit", benefits:"Yon melanj nuit lwiks pou rilaks fon ak koneksyon espirityèl. Fle dam nuit ak jasmen kreye yon pwofil gou fassinan pandan y ap endiyi kàlm.", brew:"Enfize 1–2 ti kiyè pou chak tas pou 5–7 min jis anvan ou kouche.", tip:"Kreye yon anviwonman trankil — bese limyè yo epi bwè nan silans." },
  jm: { name:"Sacred Lady of the Night Blend", benefits:"A luxurious nighttime blend fi deep relaxation and spiritual connection. Lady of di night and jasmine flowers create an enchanting flavor profile while inducing calm.", brew:"Steep 1–2 tsp per cup fi 5–7 min just before bedtime.", tip:"Create a peaceful atmosphere — dim di lights and drink in silence." },
},

22: {
  es: { name:"Mezcla de Desintoxicación y Alcalinización del Cuerpo Completo", benefits:"Una fórmula de alcalinización y limpieza profunda. El wheatgrass y el pasto de cebada son los alcalinizantes más potentes disponibles en forma de alimento.", brew:"Infusiona 2 cdta por taza durante 5 min a temperatura tibia, no caliente.", tip:"Bebe con el estómago vacío para máxima alcalinización." },
  fr: { name:"Mélange Détox Corps Entier & Alcalinisation", benefits:"Une formule d'alcalinisation et de nettoyage profond. L'herbe de blé et l'herbe d'orge sont les alcalinisants les plus puissants disponibles sous forme alimentaire.", brew:"Infusez 2 c. à café par tasse pendant 5 min à température tiède, pas chaude.", tip:"Buvez à jeun pour une alcalinisation maximale." },
  pt: { name:"Mistura Detox Corpo Inteiro e Alcalinização", benefits:"Uma fórmula de alcalinização e limpeza profunda. Grama de trigo e grama de cevada são os alcalinizantes mais potentes disponíveis como alimento.", brew:"Infunda 2 col. chá por xícara por 5 min em temperatura morna, não quente.", tip:"Beba com o estômago vazio para máxima alcalinização." },
  ht: { name:"Melanj Detoks Kò Antye ak Alkalifikasyon", benefits:"Yon fòmil alkalifikasyon ak netwayaj fon. Zèb ble ak zèb òj se alkalifye yo ki pi pwisan disponib kòm manje.", brew:"Enfize 2 ti kiyè pou chak tas pou 5 min nan tanperati cho dou, pa cho.", tip:"Bwè vant vid pou alkalifikasyon maksimòm." },
  jm: { name:"Full Body Detox & Alkalising Blend", benefits:"A deep alkalising and cleansing formula. Wheatgrass and barley grass are di most potent alkalising agents available as food.", brew:"Steep 2 tsp per cup fi 5 min at warm temperature, not hot.", tip:"Drink on an empty stomach fi maximum alkalising." },
},

23: {
  es: { name:"Mezcla del Templo del Guerrero Sagrado", benefits:"Inspirada en rituales guerreros sagrados de múltiples culturas. El eleuthero y el astragalo construyen fuerza interna duradera mientras la ashwagandha infunde coraje y resiliencia.", brew:"Infusiona 2 cdta por taza durante 10 min. Bebe por la mañana con intención.", tip:"Establece una intención antes de cada taza para amplificar el efecto." },
  fr: { name:"Mélange Temple du Guerrier Sacré", benefits:"Inspiré des rituels guerriers sacrés de multiples cultures. L'éleuthéro et l'astragale construisent une force intérieure durable tandis que l'ashwagandha insuffle courage et résilience.", brew:"Infusez 2 c. à café par tasse pendant 10 min. Buvez le matin avec intention.", tip:"Fixez une intention avant chaque tasse pour amplifier l'effet." },
  pt: { name:"Mistura Templo do Guerreiro Sagrado", benefits:"Inspirada em rituais guerreiros sagrados de múltiplas culturas. Eleuthero e astrágalo constroem força interna duradoura enquanto ashwagandha infunde coragem e resiliência.", brew:"Infunda 2 col. chá por xícara por 10 min. Beba pela manhã com intenção.", tip:"Estabeleça uma intenção antes de cada xícara para amplificar o efeito." },
  ht: { name:"Melanj Tanp Gèrye Sakre", benefits:"Enspire pa ritiyèl gèrye sakre nan anpil kilti. Eleuthero ak astragal konstwi fòs entèn dirab pandan ashwagandha enfize kouraj ak rezistans.", brew:"Enfize 2 ti kiyè pou chak tas pou 10 min. Bwè maten an ak entansyon.", tip:"Mete yon entansyon anvan chak tas pou amplifye efè a." },
  jm: { name:"Sacred Warrior Temple Blend", benefits:"Inspired by sacred warrior rituals from multiple cultures. Eleuthero and astragalus build lasting inner strength while ashwagandha infuse courage and resilience.", brew:"Steep 2 tsp per cup fi 10 min. Drink in di morning wid intention.", tip:"Set an intention before each cup to amplify di effect." },
},

24: {
  es: { name:"Mezcla Alquímica para el Equilibrio del Azúcar en Sangre", benefits:"Una fórmula clínicamente estudiada para la regulación del azúcar en sangre. La canela de Ceilán y el fenogreco mejoran la sensibilidad a la insulina mientras el berberis actúa de manera similar a la metformina en las células.", brew:"Infusiona 2 cdta por taza durante 8–10 min antes de las comidas.", tip:"Canela de Ceilán, no casia — la casia contiene cumarina que puede ser dañina en grandes cantidades." },
  fr: { name:"Mélange Alchimique Équilibre Glycémique", benefits:"Une formule cliniquement étudiée pour la régulation de la glycémie. La cannelle de Ceylan et le fenugrec améliorent la sensibilité à l'insuline tandis que la berbérine agit de manière similaire à la metformine dans les cellules.", brew:"Infusez 2 c. à café par tasse pendant 8–10 min avant les repas.", tip:"Cannelle de Ceylan, pas cassia — la cassia contient de la coumarine qui peut être nocive en grande quantité." },
  pt: { name:"Mistura Alquímica para Equilíbrio do Açúcar no Sangue", benefits:"Uma fórmula clinicamente estudada para regulação do açúcar no sangue. Canela do Ceilão e feno-grego melhoram a sensibilidade à insulina enquanto berberina age de forma semelhante à metformina nas células.", brew:"Infunda 2 col. chá por xícara por 8–10 min antes das refeições.", tip:"Canela do Ceilão, não cássia — a cássia contém cumarina que pode ser prejudicial em grandes quantidades." },
  ht: { name:"Melanj Alkimik pou Ekilibre Sik San", benefits:"Yon fòmil etidye klinikman pou regilasyon sik san. Kanèl Seylan ak fenogrèk amelyore sansibilite ensilin pandan bèberin aji menm jan ak mètfòmin nan selil yo.", brew:"Enfize 2 ti kiyè pou chak tas pou 8–10 min anvan repa.", tip:"Kanèl Seylan, pa kasia — kasia gen kumarinn ki ka nwizib nan gwo kantite." },
  jm: { name:"Alchemical Blood Sugar Balance Blend", benefits:"A clinically studied formula fi blood sugar regulation. Ceylon cinnamon and fenugreek improve insulin sensitivity while berberine act similar to metformin in di cells.", brew:"Steep 2 tsp per cup fi 8–10 min before meals.", tip:"Ceylon cinnamon, not cassia — cassia contain coumarin weh can be harmful in large amounts." },
},

25: {
  es: { name:"Mezcla para la Tiroides y el Equilibrio Endocrino", benefits:"Una mezcla de soporte tiroideo cuidadosamente elaborada. El bladderwrack proporciona yodo para la producción de hormonas tiroideas, la ashwagandha normaliza tanto el hipotiroidismo como el hipertiroidismo.", brew:"Infusiona 2 cdta por taza durante 8 min. Consulta con tu médico si estás en medicación tiroidea.", tip:"Evita el exceso de yodo si tienes hipertiroidismo — usa la mitad de la cantidad de bladderwrack." },
  fr: { name:"Mélange Thyroïde & Équilibre Endocrinien", benefits:"Un mélange de soutien thyroïdien soigneusement élaboré. Le bladderwrack fournit de l'iode pour la production d'hormones thyroïdiennes, l'ashwagandha normalise à la fois l'hypothyroïdie et l'hyperthyroïdie.", brew:"Infusez 2 c. à café par tasse pendant 8 min. Consultez votre médecin si vous prenez des médicaments thyroïdiens.", tip:"Évitez l'excès d'iode si vous avez de l'hyperthyroïdie — utilisez la moitié de la quantité de bladderwrack." },
  pt: { name:"Mistura para Tireoide e Equilíbrio Endócrino", benefits:"Uma mistura de suporte tireoidiano cuidadosamente elaborada. Bladderwrack fornece iodo para produção de hormônios tireoidianos, ashwagandha normaliza tanto o hipotireoidismo quanto o hipertireoidismo.", brew:"Infunda 2 col. chá por xícara por 8 min. Consulte seu médico se estiver em medicação tireoidiana.", tip:"Evite excesso de iodo se tiver hipertireoidismo — use metade da quantidade de bladderwrack." },
  ht: { name:"Melanj Tiroyid ak Ekilibre Endokrin", benefits:"Yon melanj sipò tiroyid ki elabore avèk swen. Bladderwrack bay iod pou pwodiksyon omon tiroyid, ashwagandha nòmalize ni ipotiroyidis ni ipèrtiroyidis.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min. Pale ak doktè ou si ou sou medikaman tiroyid.", tip:"Evite twòp iod si ou gen ipèrtiroyidis — itilize mwatye kantite bladderwrack." },
  jm: { name:"Thyroid & Endocrine Balance Blend", benefits:"A carefully crafted thyroid support blend. Bladderwrack provides iodine fi thyroid hormone production, ashwagandha normalises both hypothyroidism and hyperthyroidism.", brew:"Steep 2 tsp per cup fi 8 min. Consult yuh doctor if yuh on thyroid medication.", tip:"Avoid excess iodine if yuh have hyperthyroidism — use half di amount of bladderwrack." },
},

26: {
  es: { name:"Mezcla de Desintoxicación de Metales Pesados", benefits:"Una fórmula especializada para eliminar metales pesados del cuerpo. La clorela y el cilantro trabajan en sinergia para movilizar y unir metales pesados, mientras el cardo mariano protege el hígado durante el proceso.", brew:"Infusiona 2 cdta por taza durante 6–8 min. Bebe con mucha agua.", tip:"Comienza lentamente — la desintoxicación de metales puede causar síntomas temporales." },
  fr: { name:"Mélange Détox Métaux Lourds", benefits:"Une formule spécialisée pour éliminer les métaux lourds du corps. La chlorelle et la coriandre travaillent en synergie pour mobiliser et lier les métaux lourds, tandis que le chardon-Marie protège le foie pendant le processus.", brew:"Infusez 2 c. à café par tasse pendant 6–8 min. Buvez avec beaucoup d'eau.", tip:"Commencez lentement — la détox des métaux peut provoquer des symptômes temporaires." },
  pt: { name:"Mistura de Desintoxicação de Metais Pesados", benefits:"Uma fórmula especializada para eliminar metais pesados do corpo. Clorela e coentro trabalham em sinergia para mobilizar e ligar metais pesados, enquanto cardo-de-leite protege o fígado durante o processo.", brew:"Infunda 2 col. chá por xícara por 6–8 min. Beba com bastante água.", tip:"Comece devagar — a desintoxicação de metais pode causar sintomas temporários." },
  ht: { name:"Melanj Detoks Metal Lou", benefits:"Yon fòmil espesyalize pou elimine metal lou nan kò a. Klorèl ak kòriann travay an sinerji pou mobilize epi mare metal lou, pandan kadon lèt pwoteje fwa pandan pwosesis la.", brew:"Enfize 2 ti kiyè pou chak tas pou 6–8 min. Bwè ak anpil dlo.", tip:"Kòmanse dousman — detoks metal ka koze sentòm tanporè." },
  jm: { name:"Heavy Metal Detox Blend", benefits:"A specialised formula fi removing heavy metals from di body. Chlorella and cilantro work in synergy to mobilise and bind heavy metals, while milk thistle protect di liver during di process.", brew:"Steep 2 tsp per cup fi 6–8 min. Drink wid plenty of water.", tip:"Start slowly — metal detox can cause temporary symptoms." },
},

27: {
  es: { name:"Mezcla de Magia Lunar Femenina", benefits:"Una mezcla cíclica diseñada para honrar las fases de la luna femenina. Sincroniza los ciclos naturales con los ciclos lunares para mayor vitalidad, creatividad e intuición.", brew:"Infusiona 1–2 cdta por taza durante 7 min. Más potente cuando se bebe bajo la luz de la luna.", tip:"Intenta alinear el consumo con las fases lunares para beneficios amplificados." },
  fr: { name:"Mélange Magie Lunaire Féminine", benefits:"Un mélange cyclique conçu pour honorer les phases de la lune féminine. Synchronise les cycles naturels avec les cycles lunaires pour une plus grande vitalité, créativité et intuition.", brew:"Infusez 1–2 c. à café par tasse pendant 7 min. Plus puissant lorsqu'on le boit au clair de lune.", tip:"Essayez d'aligner la consommation avec les phases lunaires pour des bienfaits amplifiés." },
  pt: { name:"Mistura Mágica Lunar Feminina", benefits:"Uma mistura cíclica projetada para honrar as fases da lua feminina. Sincroniza os ciclos naturais com os ciclos lunares para maior vitalidade, criatividade e intuição.", brew:"Infunda 1–2 col. chá por xícara por 7 min. Mais potente quando bebido sob a luz da lua.", tip:"Tente alinhar o consumo com as fases lunares para benefícios amplificados." },
  ht: { name:"Melanj Maji Lalin Fanm", benefits:"Yon melanj siklik ki fèt pou onore faz lalin fanm. Senkronize sik natirèl ak sik lalin pou plis vitalite, kreativite ak entwiyon.", brew:"Enfize 1–2 ti kiyè pou chak tas pou 7 min. Pi pwisan lè bwè anba limyè lalin.", tip:"Eseye aliye konsòmasyon ak faz lalin pou plis benefis." },
  jm: { name:"Feminine Lunar Magic Blend", benefits:"A cyclical blend designed to honour di feminine moon phases. Synchronises natural cycles wid lunar cycles fi greater vitality, creativity and intuition.", brew:"Steep 1–2 tsp per cup fi 7 min. Most potent when drunk under moonlight.", tip:"Try to align consumption wid lunar phases fi amplified benefits." },
},

28: {
  es: { name:"Mezcla de Claridad del Chakra de la Corona", benefits:"Una mezcla de meditación de alta vibración diseñada para elevar la conciencia y conectar con la guía espiritual. Las flores sagradas y los adaptógenos suaves crean un estado de receptividad elevada.", brew:"Infusiona 1 cdta por taza durante 5–6 min. Bebe en silencio con los ojos cerrados.", tip:"Mejor tomada durante o inmediatamente antes de la meditación." },
  fr: { name:"Mélange Clarté du Chakra Couronne", benefits:"Un mélange de méditation à haute vibration conçu pour élever la conscience et se connecter à la guidance spirituelle. Les fleurs sacrées et les adaptogènes doux créent un état de réceptivité élevée.", brew:"Infusez 1 c. à café par tasse pendant 5–6 min. Buvez en silence les yeux fermés.", tip:"Mieux pris pendant ou juste avant la méditation." },
  pt: { name:"Mistura Clareza do Chakra da Coroa", benefits:"Uma mistura de meditação de alta vibração projetada para elevar a consciência e conectar com a orientação espiritual. Flores sagradas e adaptógenos suaves criam um estado de receptividade elevada.", brew:"Infunda 1 col. chá por xícara por 5–6 min. Beba em silêncio com os olhos fechados.", tip:"Melhor tomada durante ou imediatamente antes da meditação." },
  ht: { name:"Melanj Klète Chakra Kouwonn", benefits:"Yon melanj meditasyon wo vibrasyon ki fèt pou leve konsyans epi konekte ak gidans espirityèl. Fle sakre ak adaptojèn dou kreye yon eta reseptivite wo.", brew:"Enfize 1 ti kiyè pou chak tas pou 5–6 min. Bwè nan silans je fèmen.", tip:"Pi bon pran pandan oswa jis anvan meditasyon." },
  jm: { name:"Crown Chakra Clarity Blend", benefits:"A high-vibration meditation blend designed to elevate consciousness and connect wid spiritual guidance. Sacred flowers and gentle adaptogens create a state of elevated receptivity.", brew:"Steep 1 tsp per cup fi 5–6 min. Drink in silence wid eyes closed.", tip:"Best taken during or immediately before meditation." },
},

29: {
  es: { name:"Mezcla de Protección y Tierra", benefits:"Una mezcla de tierra protectora que crea una barrera energética mientras fortalece el sistema nervioso físico. Las raíces y resinas en esta fórmula han sido usadas por chamanes durante milenios.", brew:"Infusiona 2 cdta por taza durante 10 min. Bebe con los pies descalzos en la tierra si es posible.", tip:"Excelente durante períodos de estrés o cuando te sientes espiritualmente vulnerable." },
  fr: { name:"Mélange Protection & Ancrage", benefits:"Un mélange d'ancrage protecteur qui crée une barrière énergétique tout en renforçant le système nerveux physique. Les racines et résines de cette formule ont été utilisées par les chamanes depuis des millénaires.", brew:"Infusez 2 c. à café par tasse pendant 10 min. Buvez pieds nus sur la terre si possible.", tip:"Excellent pendant les périodes de stress ou lorsque vous vous sentez spirituellement vulnérable." },
  pt: { name:"Mistura de Proteção e Aterramento", benefits:"Uma mistura de aterramento protetora que cria uma barreira energética enquanto fortalece o sistema nervoso físico. Raízes e resinas nesta fórmula têm sido usadas por xamãs por milênios.", brew:"Infunda 2 col. chá por xícara por 10 min. Beba com os pés descalços na terra se possível.", tip:"Excelente durante períodos de estresse ou quando se sente espiritualmente vulnerável." },
  ht: { name:"Melanj Pwoteksyon ak Anrasinen", benefits:"Yon melanj anrasinen pwotektè ki kreye yon barye enèjik pandan li ranfòse sistèm nève fizik. Rasin ak rezin nan fòmil sa a te itilize pa chaman pou milenè.", brew:"Enfize 2 ti kiyè pou chak tas pou 10 min. Bwè pye atè sou tè si posib.", tip:"Ekselan pandan peryòd stres oswa lè ou santi espirityèlman vilnerab." },
  jm: { name:"Protection & Grounding Blend", benefits:"A protective grounding blend weh creates an energetic barrier while strengthening di physical nervous system. Roots and resins in dis formula have been used by shamans fi millennia.", brew:"Steep 2 tsp per cup fi 10 min. Drink wid bare feet on di earth if possible.", tip:"Excellent during periods of stress or when yuh feel spiritually vulnerable." },
},

30: {
  es: { name:"Mezcla de Activación del Código de la Fuente", benefits:"La mezcla más esotérica de la colección. Diseñada para quienes trabajan con energía cuántica, manifestación o prácticas espirituales avanzadas.", brew:"Infusiona 1 cdta por taza durante 6 min. Bebe durante la oración o ritual.", tip:"Establece una intención clara y específica antes de preparar esta mezcla." },
  fr: { name:"Mélange Activation du Code Source", benefits:"Le mélange le plus ésotérique de la collection. Conçu pour ceux qui travaillent avec l'énergie quantique, la manifestation ou les pratiques spirituelles avancées.", brew:"Infusez 1 c. à café par tasse pendant 6 min. Buvez pendant la prière ou le rituel.", tip:"Fixez une intention claire et spécifique avant de préparer ce mélange." },
  pt: { name:"Mistura de Ativação do Código Fonte", benefits:"A mistura mais esotérica da coleção. Projetada para quem trabalha com energia quântica, manifestação ou práticas espirituais avançadas.", brew:"Infunda 1 col. chá por xícara por 6 min. Beba durante a oração ou ritual.", tip:"Estabeleça uma intenção clara e específica antes de preparar esta mistura." },
  ht: { name:"Melanj Aktivasyon Kòd Sous", benefits:"Melanj ki pi ezoterík nan koleksyon an. Fèt pou moun ki travay ak enèji kwantik, manifestasyon oswa pratik espirityèl avanse.", brew:"Enfize 1 ti kiyè pou chak tas pou 6 min. Bwè pandan lapriyè oswa ritiyèl.", tip:"Mete yon entansyon klè ak espesifik anvan ou prepare melanj sa a." },
  jm: { name:"Source Code Activation Blend", benefits:"Di most esoteric blend in di collection. Designed fi those working wid quantum energy, manifestation or advanced spiritual practices.", brew:"Steep 1 tsp per cup fi 6 min. Drink during prayer or ritual.", tip:"Set a clear specific intention before preparing dis blend." },
},

31: {
  es: { name:"Limpieza Hepática de Leche de Cardo", benefits:"El cardo mariano contiene silimarina — uno de los hepatoprotectores más estudiados en la medicina herbal moderna. Esta mezcla regenera activamente las células hepáticas mientras filtra las toxinas.", brew:"Hierve a fuego lento 2 cdta por taza durante 15 min. Las semillas de cardo necesitan calor para extraer la silimarina.", tip:"Las semillas de cardo deben triturarse para máxima extracción — usa un molinillo de café." },
  fr: { name:"Cure Hépatique au Chardon-Marie", benefits:"Le chardon-Marie contient de la silymarine — l'un des hépatoprotecteurs les plus étudiés en phytothérapie moderne. Ce mélange régénère activement les cellules hépatiques tout en filtrant les toxines.", brew:"Faites mijoter 2 c. à café par tasse pendant 15 min. Les graines de chardon ont besoin de chaleur pour extraire la silymarine.", tip:"Les graines de chardon doivent être broyées pour une extraction maximale — utilisez un moulin à café." },
  pt: { name:"Limpeza Hepática de Cardo-de-Leite", benefits:"O cardo-de-leite contém silimarina — um dos hepatoprotetores mais estudados na fitoterapia moderna. Esta mistura regenera ativamente as células hepáticas enquanto filtra as toxinas.", brew:"Ferva em fogo baixo 2 col. chá por xícara por 15 min. As sementes de cardo precisam de calor para extrair a silimarina.", tip:"As sementes de cardo devem ser trituradas para máxima extração — use um moedor de café." },
  ht: { name:"Netwayaj Fwa Kadon Lèt", benefits:"Kadon lèt gen silymarinn — youn nan hepatoprotektè ki pi etidye nan fitoteyapi modèn. Melanj sa a aktive rejenère selil fwa pandan l ap filtre toksin.", brew:"Mijoté 2 ti kiyè pou chak tas pou 15 min. Grenn kadon bezwen chalè pou ekstrè silymarinn.", tip:"Grenn kadon dwe kraze pou maksimòm ekstraksyon — itilize yon moulen kafe." },
  jm: { name:"Milk Thistle Liver Cleanse", benefits:"Milk thistle contain silymarin — one of di most studied hepatoprotectors in modern herbal medicine. Dis blend actively regenerates liver cells while filtering toxins.", brew:"Simmer 2 tsp per cup fi 15 min. Milk thistle seeds need heat to extract di silymarin.", tip:"Milk thistle seeds must be crushed fi maximum extraction — use a coffee grinder." },
},

32: {
  es: { name:"Mezcla de Regeneración Hepática Profunda", benefits:"Un protocolo de regeneración hepática de 30 días para el daño hepático crónico, la acumulación de alcohol o el consumo prolongado de medicamentos. Activa la autofagia celular hepática para la reparación.", brew:"Hierve a fuego lento 2 cdta por taza durante 20 min. Bebe dos veces al día durante 30 días.", tip:"Evita el alcohol y los alimentos procesados durante este protocolo de limpieza." },
  fr: { name:"Mélange Régénération Hépatique Profonde", benefits:"Un protocole de régénération hépatique de 30 jours pour les lésions hépatiques chroniques, l'accumulation d'alcool ou la prise prolongée de médicaments. Active l'autophagie cellulaire hépatique pour la réparation.", brew:"Faites mijoter 2 c. à café par tasse pendant 20 min. Buvez deux fois par jour pendant 30 jours.", tip:"Évitez l'alcool et les aliments transformés pendant ce protocole de nettoyage." },
  pt: { name:"Mistura de Regeneração Hepática Profunda", benefits:"Um protocolo de regeneração hepática de 30 dias para dano hepático crônico, acúmulo de álcool ou uso prolongado de medicamentos. Ativa a autofagia celular hepática para reparo.", brew:"Ferva em fogo baixo 2 col. chá por xícara por 20 min. Beba duas vezes ao dia por 30 dias.", tip:"Evite álcool e alimentos processados durante este protocolo de limpeza." },
  ht: { name:"Melanj Rejenèrasyon Fwa Fon", benefits:"Yon pwotokòl rejenèrasyon fwa 30 jou pou domaj fwa kwonik, akimilasyon alkòl oswa itilizasyon pwolonge medikaman. Aktive otofaji selilè fwa pou reparasyon.", brew:"Mijoté 2 ti kiyè pou chak tas pou 20 min. Bwè de fwa pa jou pou 30 jou.", tip:"Evite alkòl ak manje pwoze pandan pwotokòl netwayaj sa a." },
  jm: { name:"Deep Liver Regeneration Blend", benefits:"A 30-day liver regeneration protocol fi chronic liver damage, alcohol accumulation or prolonged medication use. Activates liver cellular autophagy fi repair.", brew:"Simmer 2 tsp per cup fi 20 min. Drink twice daily fi 30 days.", tip:"Avoid alcohol and processed foods during dis cleanse protocol." },
},

33: {
  es: { name:"Flush Renal y Piedras", benefits:"Una mezcla de descongestión renal específicamente formulada para disolver cálculos renales, reducir la inflamación renal y mejorar la función del filtrado glomerular.", brew:"Infusiona 2 cdta por taza durante 10 min. Bebe 3 tazas al día con 2 litros de agua.", tip:"Este protocolo requiere hidratación adecuada — bebe al menos 8 vasos de agua al día." },
  fr: { name:"Flush Rénal & Anti-Calculs", benefits:"Un mélange de décongestion rénale spécifiquement formulé pour dissoudre les calculs rénaux, réduire l'inflammation rénale et améliorer la fonction de filtration glomérulaire.", brew:"Infusez 2 c. à café par tasse pendant 10 min. Buvez 3 tasses par jour avec 2 litres d'eau.", tip:"Ce protocole nécessite une hydratation adéquate — buvez au moins 8 verres d'eau par jour." },
  pt: { name:"Flush Renal e Pedras", benefits:"Uma mistura de descongestão renal especificamente formulada para dissolver cálculos renais, reduzir inflamação renal e melhorar a função de filtração glomerular.", brew:"Infunda 2 col. chá por xícara por 10 min. Beba 3 xícaras ao dia com 2 litros de água.", tip:"Este protocolo requer hidratação adequada — beba pelo menos 8 copos de água por dia." },
  ht: { name:"Flush Renn ak Pye Renn", benefits:"Yon melanj dekongèsyon renn ki espesyalman fòmile pou dissolve pye renn, redui enflamasyon renn epi amelyore fonksyon filtraje glomèrilè.", brew:"Enfize 2 ti kiyè pou chak tas pou 10 min. Bwè 3 tas pa jou ak 2 lit dlo.", tip:"Pwotokòl sa a mande idrasyon kòrèk — bwè omwen 8 vè dlo pa jou." },
  jm: { name:"Kidney Flush & Stone Blend", benefits:"A kidney decongestion blend specifically formulated to dissolve kidney stones, reduce kidney inflammation and improve glomerular filtration function.", brew:"Steep 2 tsp per cup fi 10 min. Drink 3 cups daily wid 2 litres of water.", tip:"Dis protocol requires adequate hydration — drink at least 8 glasses of water daily." },
},

34: {
  es: { name:"Restaurador Alcalino Renal", benefits:"Diseñado para restaurar el pH alcalino en los riñones. La cáscara de sandía y la raíz de malvavisco forman la base — ambas son diuréticas suaves que apoyan la filtración renal sin estrés.", brew:"Infusiona 2 cdta por taza durante 8 min. Bebe entre comidas.", tip:"La cáscara de sandía seca es el ingrediente activo más potente — no lo omitas." },
  fr: { name:"Restaurateur Rénal Alcalin", benefits:"Conçu pour restaurer le pH alcalin dans les reins. L'écorce de pastèque et la racine de guimauve forment la base — toutes deux sont des diurétiques doux qui soutiennent la filtration rénale sans stress.", brew:"Infusez 2 c. à café par tasse pendant 8 min. Buvez entre les repas.", tip:"L'écorce de pastèque séchée est l'ingrédient actif le plus puissant — ne l'omettez pas." },
  pt: { name:"Restaurador Renal Alcalino", benefits:"Projetado para restaurar o pH alcalino nos rins. Casca de melancia e raiz de marshmallow formam a base — ambos são diuréticos suaves que apoiam a filtração renal sem estresse.", brew:"Infunda 2 col. chá por xícara por 8 min. Beba entre as refeições.", tip:"A casca de melancia seca é o ingrediente ativo mais potente — não a omita." },
  ht: { name:"Restorè Renn Alkalen", benefits:"Fèt pou restore pH alkalen nan renn yo. Ekòs melon dlo ak rasin marshmallow fòme baz la — toulede se dyirètik dou ki sipòte filtraje renn san stres.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min. Bwè ant repa.", tip:"Ekòs melon dlo sèk se engredyan aktif ki pi pwisan — pa kite l deyò." },
  jm: { name:"Alkaline Kidney Restore Blend", benefits:"Designed to restore alkaline pH in di kidneys. Watermelon rind and marshmallow root form di base — both are gentle diuretics weh support kidney filtration without stress.", brew:"Steep 2 tsp per cup fi 8 min. Drink between meals.", tip:"Dried watermelon rind is di most potent active ingredient — don't leave it out." },
},

35: {
  es: { name:"Limpiador de Sangre de Trébol Rojo Hepático", benefits:"El trébol rojo es una de las plantas más antiguas usadas para purificar la sangre. Rica en isoflavonas que apoyan el equilibrio hormonal mientras la raíz de bardana elimina activamente las toxinas de la sangre.", brew:"Infusiona 2 cdta por taza durante 8–10 min. Mejor tomada por la mañana en ayunas.", tip:"Evita durante el embarazo — el trébol rojo tiene propiedades estrogénicas." },
  fr: { name:"Purificateur Sanguin Foie Trèfle Rouge", benefits:"Le trèfle rouge est l'une des plantes les plus anciennes utilisées pour purifier le sang. Riche en isoflavones qui soutiennent l'équilibre hormonal tandis que la racine de bardane élimine activement les toxines du sang.", brew:"Infusez 2 c. à café par tasse pendant 8–10 min. Mieux pris le matin à jeun.", tip:"Évitez pendant la grossesse — le trèfle rouge a des propriétés œstrogéniques." },
  pt: { name:"Purificador de Sangue Hepático de Trevo Vermelho", benefits:"O trevo vermelho é uma das plantas mais antigas usadas para purificar o sangue. Rico em isoflavonas que apoiam o equilíbrio hormonal enquanto raiz de bardana elimina ativamente toxinas do sangue.", brew:"Infunda 2 col. chá por xícara por 8–10 min. Melhor tomado pela manhã em jejum.", tip:"Evite durante a gravidez — o trevo vermelho tem propriedades estrogênicas." },
  ht: { name:"Pirifye San Fwa Trefle Wouj", benefits:"Trefle wouj se youn nan pi ansyen plant itilize pou pirify san. Rich nan isoflavòn ki sipòte ekilibre ormonal pandan rasin bàdann aktive elimine toksin nan san.", brew:"Enfize 2 ti kiyè pou chak tas pou 8–10 min. Pi bon pran maten an vant vid.", tip:"Evite pandan gwosès — trefle wouj gen pwopriyete estrojènik." },
  jm: { name:"Red Clover Liver Blood Purifier", benefits:"Red clover is one of di oldest plants used fi purifying di blood. Rich in isoflavones weh support hormonal balance while burdock root actively removes toxins from di blood.", brew:"Steep 2 tsp per cup fi 8–10 min. Best taken in di morning on an empty stomach.", tip:"Avoid during pregnancy — red clover has oestrogenic properties." },
},

36: {
  es: { name:"Limpieza Hepática y Renal Maestra Definitiva", benefits:"El protocolo de limpieza más completo de la colección — diseñado para una limpieza profunda de 21 días de hígado y riñones. Combina los hepatoprotectores y los depurativos renales más potentes de la naturaleza.", brew:"Hierve a fuego lento 2 cdta por taza durante 15–20 min. Bebe dos veces al día durante 21 días.", tip:"Este es un protocolo serio — consulta con un proveedor de salud antes de comenzar si tienes condiciones hepáticas o renales." },
  fr: { name:"Cure Maîtresse Ultime Foie & Reins", benefits:"Le protocole de nettoyage le plus complet de la collection — conçu pour un nettoyage profond de 21 jours du foie et des reins. Combine les hépatoprotecteurs et les dépuratifs rénaux les plus puissants de la nature.", brew:"Faites mijoter 2 c. à café par tasse pendant 15–20 min. Buvez deux fois par jour pendant 21 jours.", tip:"C'est un protocole sérieux — consultez un professionnel de santé avant de commencer si vous avez des conditions hépatiques ou rénales." },
  pt: { name:"Limpeza Mestra Definitiva do Fígado e Rins", benefits:"O protocolo de limpeza mais abrangente da coleção — projetado para uma limpeza profunda de 21 dias de fígado e rins. Combina os hepatoprotetores e depurativos renais mais potentes da natureza.", brew:"Ferva em fogo baixo 2 col. chá por xícara por 15–20 min. Beba duas vezes ao dia por 21 dias.", tip:"Este é um protocolo sério — consulte um profissional de saúde antes de começar se tiver condições hepáticas ou renais." },
  ht: { name:"Netwayaj Mèt Definitif Fwa ak Renn", benefits:"Pwotokòl netwayaj ki pi konplè nan koleksyon an — fèt pou yon netwayaj fon 21 jou fwa ak renn. Konbine hepatoprotektè yo ak pirifye renn ki pi pwisan nan nati.", brew:"Mijoté 2 ti kiyè pou chak tas pou 15–20 min. Bwè de fwa pa jou pou 21 jou.", tip:"Se yon pwotokòl serye — pale ak yon pwofesyonèl sante anvan kòmanse si ou gen kondisyon fwa oswa renn." },
  jm: { name:"Ultimate Liver & Kidney Master Cleanse", benefits:"Di most comprehensive cleanse protocol in di collection — designed fi a deep 21-day liver and kidney cleanse. Combines di most potent hepatoprotectors and kidney cleansers in nature.", brew:"Simmer 2 tsp per cup fi 15–20 min. Drink twice daily fi 21 days.", tip:"Dis is a serious protocol — consult a health provider before starting if yuh have liver or kidney conditions." },
},

37: {
  es: { name:"Mezcla de Apoyo Linfático", benefits:"El sistema linfático elimina los desechos celulares del cuerpo — pero a diferencia del corazón, no tiene su propia bomba. Esta mezcla estimula el flujo linfático para reducir la hinchazón, apoyar la inmunidad y limpiar la piel.", brew:"Infusiona 2 cdta por taza durante 7–8 min. Bebe 2 tazas al día.", tip:"Combina con ejercicio suave o reboting para máximo movimiento linfático." },
  fr: { name:"Mélange Soutien Lymphatique", benefits:"Le système lymphatique élimine les déchets cellulaires du corps — mais contrairement au cœur, il n'a pas sa propre pompe. Ce mélange stimule le flux lymphatique pour réduire les gonflements, soutenir l'immunité et clarifier la peau.", brew:"Infusez 2 c. à café par tasse pendant 7–8 min. Buvez 2 tasses par jour.", tip:"Combinez avec de l'exercice doux ou du rebounding pour un mouvement lymphatique maximal." },
  pt: { name:"Mistura de Suporte Linfático", benefits:"O sistema linfático remove resíduos celulares do corpo — mas ao contrário do coração, não tem sua própria bomba. Esta mistura estimula o fluxo linfático para reduzir inchaço, apoiar a imunidade e clarear a pele.", brew:"Infunda 2 col. chá por xícara por 7–8 min. Beba 2 xícaras ao dia.", tip:"Combine com exercício suave ou reboting para máximo movimento linfático." },
  ht: { name:"Melanj Sipò Lenfatik", benefits:"Sistèm lenfatik retire dechè selilè nan kò a — men kontrèman ak kè a, li pa gen ponp pa li. Melanj sa a stimile flou lenfatik pou redui anfle, sipòte iminite epi klere po.", brew:"Enfize 2 ti kiyè pou chak tas pou 7–8 min. Bwè 2 tas pa jou.", tip:"Konbine ak ekzèsis dou oswa reboting pou maksimòm mouvman lenfatik." },
  jm: { name:"Lymphatic Support Blend", benefits:"Di lymphatic system removes cellular waste from di body — but unlike di heart, it has no pump of its own. Dis blend stimulates lymphatic flow to reduce swelling, support immunity and clear di skin.", brew:"Steep 2 tsp per cup fi 7–8 min. Drink 2 cups daily.", tip:"Combine wid gentle exercise or rebounding fi maximum lymphatic movement." },
},

38: {
  es: { name:"Mezcla Restauradora Renal Alcalina", benefits:"Diseñada para restaurar el pH óptimo en el tejido renal. Las investigaciones muestran que los riñones funcionan mejor en un ambiente ligeramente alcalino — esta mezcla proporciona ese ambiente.", brew:"Infusiona 2 cdta por taza durante 8 min. Bebe entre comidas.", tip:"Evita la cafeína, el azúcar y los alimentos ácidos durante este protocolo." },
  fr: { name:"Mélange Restaurateur Rénal Alcalin", benefits:"Conçu pour restaurer le pH optimal dans le tissu rénal. Les recherches montrent que les reins fonctionnent mieux dans un environnement légèrement alcalin — ce mélange fournit cet environnement.", brew:"Infusez 2 c. à café par tasse pendant 8 min. Buvez entre les repas.", tip:"Évitez la caféine, le sucre et les aliments acides pendant ce protocole." },
  pt: { name:"Mistura Restauradora Renal Alcalina", benefits:"Projetada para restaurar o pH ideal no tecido renal. Pesquisas mostram que os rins funcionam melhor em um ambiente levemente alcalino — esta mistura fornece esse ambiente.", brew:"Infunda 2 col. chá por xícara por 8 min. Beba entre as refeições.", tip:"Evite cafeína, açúcar e alimentos ácidos durante este protocolo." },
  ht: { name:"Melanj Restorè Renn Alkalen", benefits:"Fèt pou restore pH optimal nan tisi renn. Rechèch montre renn yo fonksyone pi byen nan yon anviwonman yon ti kras alkalen — melanj sa a bay anviwonman sa a.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min. Bwè ant repa.", tip:"Evite kafeyèn, sik ak manje asid pandan pwotokòl sa a." },
  jm: { name:"Alkaline Kidney Restore Blend", benefits:"Designed to restore optimal pH in kidney tissue. Research shows kidneys function best in a slightly alkaline environment — dis blend provides dat environment.", brew:"Steep 2 tsp per cup fi 8 min. Drink between meals.", tip:"Avoid caffeine, sugar and acidic foods during dis protocol." },
},

39: {
  es: { name:"Purificador de Sangre Hepática de Trébol Rojo", benefits:"El trébol rojo es una de las plantas más antiguas usadas para purificar la sangre y la medicina hepática. Esta fórmula combina su potencia con limpiadores de sangre complementarios.", brew:"Infusiona 2 cdta por taza durante 8 min. Mejor en ayunas.", tip:"Toma durante 3 semanas, luego toma 1 semana de descanso." },
  fr: { name:"Purificateur Sanguin Hépatique Trèfle Rouge", benefits:"Le trèfle rouge est l'une des plantes les plus anciennes utilisées pour purifier le sang et la médecine hépatique. Cette formule combine sa puissance avec des dépuratifs sanguins complémentaires.", brew:"Infusez 2 c. à café par tasse pendant 8 min. Mieux à jeun.", tip:"Prenez pendant 3 semaines, puis prenez 1 semaine de repos." },
  pt: { name:"Purificador de Sangue Hepático de Trevo Vermelho", benefits:"O trevo vermelho é uma das plantas mais antigas usadas para purificar o sangue e na medicina hepática. Esta fórmula combina seu potencial com purificadores de sangue complementares.", brew:"Infunda 2 col. chá por xícara por 8 min. Melhor em jejum.", tip:"Tome por 3 semanas, depois faça 1 semana de descanso." },
  ht: { name:"Pirifye San Epatik Trefle Wouj", benefits:"Trefle wouj se youn nan pi ansyen plant itilize pou pirify san ak medsin fwa. Fòmil sa a konbine pisans li ak pirifye san konplemantè.", brew:"Enfize 2 ti kiyè pou chak tas pou 8 min. Pi bon vant vid.", tip:"Pran pou 3 semèn, Epi pran 1 semèn repo." },
  jm: { name:"Red Clover Liver Blood Purifier", benefits:"Red clover is one of di oldest plants used fi purifying di blood and liver medicine. Dis formula combines its potency wid complementary blood cleansers.", brew:"Steep 2 tsp per cup fi 8 min. Best on an empty stomach.", tip:"Take fi 3 weeks, then take 1 week off." },
},

40: {
  es: { name:"Limpieza Maestra Definitiva de Hígado y Riñón", benefits:"El protocolo de limpieza más completo de la colección — 21 días de regeneración profunda del hígado y los riñones. Todo en una sola fórmula potente.", brew:"Hierve a fuego lento 2 cdta durante 15–20 min. Dos veces al día durante 21 días.", tip:"Protocolo serio — consulta con un profesional de salud si tienes condiciones hepáticas o renales existentes." },
  fr: { name:"Cure Maîtresse Ultime Foie & Rein", benefits:"Le protocole de nettoyage le plus complet de la collection — 21 jours de régénération profonde du foie et des reins. Tout en une seule formule puissante.", brew:"Faites mijoter 2 c. à café pendant 15–20 min. Deux fois par jour pendant 21 jours.", tip:"Protocole sérieux — consultez un professionnel de santé si vous avez des conditions hépatiques ou rénales existantes." },
  pt: { name:"Limpeza Mestra Definitiva de Fígado e Rim", benefits:"O protocolo de limpeza mais abrangente da coleção — 21 dias de regeneração profunda do fígado e rins. Tudo em uma única fórmula potente.", brew:"Ferva em fogo baixo 2 col. chá por 15–20 min. Duas vezes ao dia por 21 dias.", tip:"Protocolo sério — consulte um profissional de saúde se tiver condições hepáticas ou renais existentes." },
  ht: { name:"Netwayaj Mèt Definitif Fwa ak Renn", benefits:"Pwotokòl netwayaj ki pi konplè nan koleksyon an — 21 jou rejenèrasyon fon fwa ak renn. Tout nan yon sèl fòmil pwisan.", brew:"Mijoté 2 ti kiyè pou 15–20 min. De fwa pa jou pou 21 jou.", tip:"Pwotokòl serye — pale ak yon pwofesyonèl sante si ou gen kondisyon fwa oswa renn egzistan." },
  jm: { name:"Ultimate Liver & Kidney Master Cleanse", benefits:"Di most comprehensive cleanse protocol in di collection — 21 days of deep liver and kidney regeneration. Everything in one potent formula.", brew:"Simmer 2 tsp fi 15–20 min. Twice daily fi 21 days.", tip:"Serious protocol — consult a health provider if yuh have existing liver or kidney conditions." },
},

};

/**
 * Get translated Tea Library blend content.
 * Returns null for English — component uses original data.
 */
export function getTLBlend(n, lang) {
  if (!lang || lang === 'en') return null;
  return TL_TRANS[n]?.[lang] || null;
}

export default TL_TRANS;
